# Generated by Django 3.1.1 on 2020-12-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='listName',
            new_name='name',
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('explanation', models.CharField(max_length=100, verbose_name='Item Explanation')),
                ('deadline', models.DateTimeField(verbose_name='Item Deadline')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Item Created Date')),
                ('status', models.BooleanField(verbose_name='is Complete?')),
                ('tList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.list', verbose_name='List')),
            ],
            options={
                'verbose_name': 'Todo List Item',
                'verbose_name_plural': 'Todo List Items',
            },
        ),
    ]
